import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import { Container, Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./QueryClientProvider";
import Provider from "./ThemeProvider";
import ManagedProvider from "./ManagedProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body classNames={inter.variable}>
        <QueryClientProvider>
          <AuthProvider>
            <Provider>
              <ManagedProvider>{children}</ManagedProvider>
            </Provider>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
